# Generated by Django 6.0 on 2025-12-20 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_booking_advance_paid_booking_coming_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='Atithi Hotel', max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=15, verbose_name='GST Identification Number')),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('room_tax_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='Default Room GST %', max_digits=5)),
            ],
            options={
                'verbose_name': 'Property Setting',
                'verbose_name_plural': 'Property Settings',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('UTILITY', 'Electricity/Water'), ('SALARY', 'Staff Salaries'), ('MAINTENANCE', 'Repairs & Maintenance'), ('INVENTORY', 'Supplies & Grocery'), ('TAX', 'Govt Taxes/Fees'), ('OTHER', 'Miscellaneous')], default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
