# Generated by Django 6.0 on 2025-12-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_hotel_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Atithi SaaS Corp', max_length=100)),
                ('support_email', models.EmailField(default='support@atithi.com', max_length=254)),
                ('support_phone', models.CharField(default='+91 99999 88888', max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(default='Tech Park, Bangalore, India')),
                ('software_version', models.CharField(default='v2.5', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Software Company Settings',
                'verbose_name_plural': 'Software Company Settings',
            },
        ),
    ]
